package(default_visibility = ["//visibility:public"])

cc_library(
    name = "nvhashtable",
    hdrs = [
        "nv_hashtable.cuh",
        "nv_util.h",
        "cudf/concurrent_unordered_map.cuh",
        "cudf/hash_functions.cuh",
        "cudf/managed_allocator.cuh",
        "cudf/managed.cuh",
    ],
)